version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: halal_frontend
    volumes:
      - ./src/:/app
    tty: true
    environment:
     - WATCHPACK_POLLING=true
    command: sh -c "yarn && yarn dev"
    ports:
     - "3000:3000"